# Generated by Django 4.0.6 on 2022-07-24 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)]))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
