# Generated by Django 4.0.6 on 2022-07-28 01:14

import django.core.validators
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_booked_seats_alter_event_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)]))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=25, validators=[events.models.validate_name]),
        ),
    ]
