# Generated by Django 4.0.6 on 2022-07-28 01:20

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_booked_seats_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0, validators=[events.models.Event.clean]),
        ),
    ]
