# Generated by Django 4.0.6 on 2022-07-28 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_booked_seats_alter_event_num_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
